### ISSUE TITLE
Dedupe SQL script not detecting resolution

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#128]
Hi, I started running into this issue when working on Dedupe Refresh.
I created a test data with a few data values resulting into 4 dedupes. Two of them are resolved.

I have an issue that sometime the SQL script doesn't recognize that the two dedupes already have been resolved.

>> Issue
![image](https://user-images.githubusercontent.com/47790868/98302342-36301200-1f8a-11eb-811b-99a95edccc0a.png)
(not resolved)

SQL output:
https://dev-jakub.datim.org/api/sqlViews/wzpSd6j89wc/data?cacheBuster=1604614445616&paging=false&var=ou:PqlFzhuPcF1&var=pe:2020Q2&var=rs:true&var=ps:50&var=pg:1&var=dt:RESULTS&var=ty:PURE&var=ag:NONE&var=dg:NONE

![image](https://user-images.githubusercontent.com/47790868/98302673-d38b4600-1f8a-11eb-8b24-653f1e3397a3.png)

This is a link to `dataValueSets` output for debugging:
https://dev-jakub.datim.org/api/dataValueSets.json?orgUnit=p7M264Wg1qB&period=2020Q2&dataSet=qzVASYuaIey

>> Expected behavior

I believe the three rows from the SQL output should all be marked as `RESOLVED`

Sometime the script would do it. But now it doesn't.

**Comment by hardingt** [comment]
@jakub-bao I believe that this may be related to the timing of the values

```sql
/*Duplication status*/
/*Only resolve non-legacy dedupes*/
 ALTER TABLE temp1 ADD COLUMN duplication_status character varying(50) DEFAULT 'UNRESOLVED';
/*Only resolve non-legacy dedupes*/
EXECUTE format('UPDATE temp1 set duplication_status = ''RESOLVED''
WHERE group_id NOT IN (SELECT a.group_id FROM (
SELECT group_id,lastupdated as dedupe_time from temp1
WHERE attributeoptioncomboid = %L ) a
INNER JOIN (
SELECT group_id,MAX(lastupdated) as data_time from temp1
WHERE attributeoptioncomboid != %L
GROUP BY group_id ) b
on a.group_id = b.group_id
WHERE a.dedupe_time <  b.data_time
 )
AND group_id IN (SELECT DISTINCT group_id from temp1 where value ~(''^[-|0]'') and
  attributeoptioncomboid = %L)',pure_id,pure_id,pure_id);
```

I don't fully understand this section of the code yet, but I believe it means that if the dedupe record is newer than the last entered value: `SELECT group_id,MAX(lastupdated) as data_time from temp1` 

Sure enough when I altered the lastupdated by 1 minute for your dedupe record -30010 it now shows up as resolved.

![image](https://user-images.githubusercontent.com/11567315/98319284-6ab5c500-1fae-11eb-9f91-d130cd06fd43.png)

Dedupe records are rarely imported, and there is a real reason to alert a user to a dedupe record as being "unresolved" if their dedupe is _older_ than the last entered value, because it means that their dedupe didn't take into account all the relevant information. There is actually a cron that runs each night to clear these dedupes out in production as well. Best when you create test data to make sure the dedupe record is a second or more later than the datavalues themselves. The way that query is written it doesn't look it would be simple to make a `>` into a `>=`.

**Comment by hardingt** [comment]
BTW, I understand that my final paragraph up there looks like gibberish. @jason-p-pickering what have we done.

**Comment by jason-p-pickering** [comment]
Tried to decipher the Rosetta stone?😏

But yes... Dedupe values must be as young or younger when compared with their components.
